version: '3.8'

services:
  # MongoDB
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  # Redis
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"       # AMQP protocol port
      - "15672:15672"     # Management console port
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 1234
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  backend:
    build:
      context: ./perfect_date_be_main
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017/perfect_date
      - REDIS_URI=redis://redis:6379
      - RABBITMQ_URI=amqp://root:1234@rabbitmq:5672
    ports:
      - "8080:8080"
    volumes:
    - ./perfect_date_be_main:/app
    depends_on:
      - mongo
      - redis
      - rabbitmq

  mail-microservice:
    build:
      context: ./mail-microservice
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
    - RABBITMQ_URI=amqp://root:1234@rabbitmq:5672
    volumes:
    - ./mail-microservice:/app
    depends_on:
      - rabbitmq

# Volumes
volumes:
  redis_data:
  rabbitmq_data:
